<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="KSAGEffects.props" />
	<PropertyGroup>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
		<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
		<TargetFramework>net10.0</TargetFramework>
		<TargetFrameworkVersion>net10.0</TargetFrameworkVersion>
		<LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<LangVersion>latest</LangVersion>
		<OutputPath>bin\$(Configuration)</OutputPath>
		<AssemblyName>$(ModName)</AssemblyName>
		<OutputType>Library</OutputType>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release;PerfDebug</Configurations>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

		<VersionPrefix>0.1.5</VersionPrefix>
		<Version>$(VersionPrefix)</Version>
		<AssemblyVersion>0.1.1.0</AssemblyVersion>
		<FileVersion>$(VersionPrefix).0</FileVersion>

		<GitShortHash>nogit</GitShortHash>
		<InformationalVersionPostfix></InformationalVersionPostfix>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

		<Company>AMPW</Company>
		<Authors>AMPW</Authors>
		<Copyright>GNU GPL v3.0</Copyright>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='PerfDebug|AnyCPU'">
		<DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<InformationalVersionPostfix>-debug</InformationalVersionPostfix>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='PerfDebug'">
		<InformationalVersionPostfix>-perfDebug</InformationalVersionPostfix>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="StarMap.API" Version="0.3.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\GEffectsLogic\GEffectsLogic\GEffectsLogic.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="KittenExtensions">
			<HintPath>..\..\..\..\Documents\My Games\Kitten Space Agency\mods\KittenExtensions\KittenExtensions.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="ShaderExtensions">
			<HintPath>..\..\..\..\Documents\My Games\Kitten Space Agency\mods\ShaderExtensions\ShaderExtensions.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="GEffectAssests.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Shaders\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Patches\**\*.*">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="mod.toml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
	<Target Name="SetVersionMetadata" BeforeTargets="GetAssemblyVersion">
		<Exec Command="git rev-parse --short HEAD" ConsoleToMSBuild="true" IgnoreExitCode="true" IgnoreStandardErrorWarningFormat="true">
		<Output TaskParameter="ConsoleOutput" PropertyName="GitShortHashRaw" />
		</Exec>

		<PropertyGroup>
		<GitShortHash Condition="'$(GitShortHashRaw)' != ''">$([System.String]::Copy('$(GitShortHashRaw)').Trim())</GitShortHash>
		<GitShortHash Condition="'$(GitShortHash)' == ''">nogit</GitShortHash>
		<InformationalVersion>v$(VersionPrefix).$(GitShortHash)$(InformationalVersionPostfix)</InformationalVersion>
		<ProductVersion>$(InformationalVersion)</ProductVersion>
		</PropertyGroup>
	</Target>

	<Import Project="CopyOutput.targets" />
</Project>
